spring.application.name=spvmcart

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# MySQL Driver - Sping detects driver class automatically
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/spvmcart
spring.datasource.username=root
spring.datasource.password=pass123